---
- name: restart gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when
  until: gitlab_restart is not failed
  retries: 3
  delay: 10
